// DESIGN.md parser and generator

import * as fs from 'fs';
import * as path from 'path';
import { DesignConfig, InitAnswers } from '../types';

const DESIGN_MD_FILENAME = 'DESIGN.md';

// ── Generator ────────────────────────────────────────────────────────────────

/** Creates the DESIGN.md content from user answers */
export function generateDesignMd(answers: InitAnswers): string {
  const now = new Date().toISOString();

  return `# StyleKit Design Configuration
> Auto-generated by StyleKit CLI on ${now}

## Project
- **Name:** ${answers.projectName}
- **Style Preference:** ${answers.stylePreference}

## Colors
- **Primary Color:** ${answers.primaryColor}

## Typography
- **Font Family:** ${answers.fontFamily}

## Design Notes
<!-- Add any extra design notes here. StyleKit will include these in AI prompts. -->

## StyleKit Metadata
\`\`\`json
{
  "projectName": "${answers.projectName}",
  "primaryColor": "${answers.primaryColor}",
  "fontFamily": "${answers.fontFamily}",
  "stylePreference": "${answers.stylePreference}",
  "generatedAt": "${now}"
}
\`\`\`
`;
}

// ── Writer ───────────────────────────────────────────────────────────────────

/** Writes DESIGN.md to the given directory */
export function writeDesignMd(dir: string, content: string): void {
  const filePath = path.join(dir, DESIGN_MD_FILENAME);
  fs.writeFileSync(filePath, content, 'utf8');
}

/** Returns true if DESIGN.md exists in the given directory */
export function designMdExists(dir: string): boolean {
  return fs.existsSync(path.join(dir, DESIGN_MD_FILENAME));
}

// ── Parser ───────────────────────────────────────────────────────────────────

/** Parses DESIGN.md and extracts the metadata JSON block */
export function parseDesignMd(dir: string): DesignConfig | null {
  const filePath = path.join(dir, DESIGN_MD_FILENAME);

  if (!fs.existsSync(filePath)) {
    return null;
  }

  const content = fs.readFileSync(filePath, 'utf8');

  // Extract JSON from the fenced code block
  const match = content.match(/```json\s*([\s\S]*?)```/);
  if (!match || !match[1]) {
    return null;
  }

  try {
    return JSON.parse(match[1].trim()) as DesignConfig;
  } catch {
    return null;
  }
}

// ── Prompt generator ─────────────────────────────────────────────────────────

/** Turns a DesignConfig into an AI prompt snippet */
export function buildAiPrompt(config: DesignConfig): string {
  return `You are helping me build a UI. Please follow this design system strictly:

## Design System
- **Project:** ${config.projectName}
- **Style:** ${config.stylePreference}
- **Primary Color:** ${config.primaryColor}
- **Font Family:** ${config.fontFamily}

## Design Principles
${getStylePrinciples(config.stylePreference)}

## Implementation Notes
- Use the primary color (${config.primaryColor}) for CTAs, highlights, and key interactive elements.
- Use ${config.fontFamily} as the primary typeface. Apply it via the font-sans utility class.
- Follow the ${config.stylePreference} aesthetic consistently — avoid mixing opposing design languages.
- Keep spacing generous and consistent. Prefer rem units.
- Ensure WCAG AA accessibility contrast ratios.
${config.skill ? `- Reference the "${config.skill}" StyleKit skill for the full token set.\n` : ''}
Please apply these guidelines to all components and layouts you generate.`;
}

function getStylePrinciples(style: string): string {
  const principles: Record<string, string> = {
    minimal: '- Remove everything unnecessary. White space is your friend.\n- One accent color, used sparingly.\n- Borders instead of shadows where possible.',
    corporate: '- Structured grid layouts. Professional tone.\n- Conservative color usage. Navy and grey dominate.\n- Readable body text is paramount.',
    startup: '- Bold headlines. Clear value proposition.\n- Gradient accents allowed on CTAs.\n- Plenty of social proof sections.',
    'dark-mode': '- Dark backgrounds (#0f172a or similar). Light text.\n- Blue or teal accent colors pop well.\n- Subtle borders to define sections.',
    glassmorphism: '- Use backdrop-blur for glass panels.\n- Semi-transparent backgrounds: rgba(255,255,255,0.1).\n- Vibrant gradient backgrounds behind glass layers.',
    retro: '- Monospace fonts everywhere.\n- Green-on-black or amber-on-black terminal aesthetic.\n- Pixel borders. No border-radius.',
    brutalist: '- Thick black borders. No border-radius.\n- High contrast. Black and white plus one vivid accent.\n- Offset box shadows (e.g., 4px 4px 0 #000).',
    'soft-ui': '- Neumorphic shadows: light top-left, dark bottom-right.\n- Background and element colors nearly identical.\n- Avoid harsh blacks; use dark greys.',
    neon: '- Dark near-black background.\n- Neon glow via box-shadow on key elements.\n- Cyberpunk typography (Orbitron, Share Tech Mono).',
    ocean: '- Blues and teals. Flowing, rounded shapes.\n- Calming whitespace. Soft gradients.\n- Serif headings for warmth.',
  };

  return principles[style] ?? '- Follow the chosen aesthetic consistently throughout all components.';
}
