import CodeBlock from './CodeBlock'

const sampleDesignMd = `# DESIGN.md — Vercel
> Generated by StyleKit on 2025-01-15

## Colors
primary: #000000
background: #ffffff
accent: #0070f3
muted: #888888
border: #eaeaea

## Typography
font-sans: Inter, system-ui, sans-serif
font-mono: "Fira Code", monospace
text-base: 16px / 1.6
heading-xl: 64px / 1.1 / -0.04em

## Spacing
space-1: 4px
space-2: 8px
space-4: 16px
space-8: 32px

## Border Radius
radius-sm: 4px
radius-md: 8px
radius-lg: 12px`

export default function Hero() {
  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden pt-16">
      {/* Background glow orbs */}
      <div className="absolute inset-0 bg-zinc-950" />
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-[60%] w-[800px] h-[500px] rounded-full bg-violet-600/10 blur-[120px]" />
        <div className="absolute top-1/3 left-1/4 w-[350px] h-[350px] rounded-full bg-violet-800/8 blur-[80px]" />
        <div className="absolute top-1/3 right-1/4 w-[250px] h-[250px] rounded-full bg-indigo-500/6 blur-[60px]" />
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-12 pb-16 md:pt-16 md:pb-24">
        <div className="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          {/* Left: Text */}
          <div className="text-center lg:text-left">
            {/* Badge */}
            <div className="inline-flex items-center gap-2 px-3 py-1.5 mb-8 rounded-full border border-violet-500/30 bg-violet-500/10 text-violet-300 text-xs font-medium">
              <span className="w-1.5 h-1.5 rounded-full bg-violet-400 animate-pulse" />
              Chrome Extension + CLI — Free to start
            </div>

            {/* Heading */}
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold leading-[1.1] tracking-tight mb-6">
              <span className="gradient-text">Extract Any Website&apos;s</span>
              <br />
              <span className="gradient-text">Design System</span>
              <br />
              <span className="gradient-text-violet">in One Click</span>
            </h1>

            {/* Subheading */}
            <p className="text-lg text-zinc-400 leading-relaxed mb-8 max-w-xl mx-auto lg:mx-0">
              StyleKit analyzes any webpage and generates{' '}
              <span className="text-zinc-200 font-medium">AI-ready DESIGN.md files</span>{' '}
              for Claude Code, Cursor, Copilot and more. Stop guessing design tokens — extract them instantly.
            </p>

            {/* CTAs */}
            <div className="flex flex-col sm:flex-row gap-3 justify-center lg:justify-start mb-6">
              <a
                href="https://chromewebstore.google.com/detail/stylekit/jbbngpjghnifmnmlfcjacooakmhhglge"
                className="group flex items-center justify-center gap-2.5 px-6 py-3.5 bg-violet-600 hover:bg-violet-500 text-white font-semibold rounded-xl transition-all duration-200 shadow-lg shadow-violet-900/40 hover:shadow-violet-900/60 hover:-translate-y-0.5"
              >
                <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 14.5v-9l6 4.5-6 4.5z"/>
                </svg>
                Add to Chrome — Free
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="group-hover:translate-x-0.5 transition-transform">
                  <path d="M5 12h14M12 5l7 7-7 7"/>
                </svg>
              </a>
              <a
                href="/docs"
                className="flex items-center justify-center gap-2 px-6 py-3.5 border border-zinc-700 hover:border-zinc-500 text-zinc-300 hover:text-white font-medium rounded-xl transition-all duration-200 hover:bg-white/5"
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                  <polyline points="14 2 14 8 20 8"/>
                  <line x1="16" y1="13" x2="8" y2="13"/>
                  <line x1="16" y1="17" x2="8" y2="17"/>
                  <polyline points="10 9 9 9 8 9"/>
                </svg>
                View Docs
              </a>
            </div>

            {/* Social proof */}
            <p className="text-xs text-zinc-600">
              Works with any website&nbsp;&nbsp;·&nbsp;&nbsp;No account required&nbsp;&nbsp;·&nbsp;&nbsp;Free forever
            </p>

            <a href="https://www.producthunt.com/posts/stylekit-2" target="_blank" rel="noopener noreferrer" className="inline-block mt-4">
              <img
                src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=stylekit-2&theme=dark"
                alt="StyleKit on Product Hunt"
                width="250"
                height="54"
              />
            </a>

            {/* CLI snippet */}
            <div className="mt-8 flex items-center gap-3 p-3.5 rounded-xl bg-zinc-900/80 border border-zinc-800 max-w-sm mx-auto lg:mx-0">
              <div className="flex-shrink-0 w-7 h-7 rounded-md bg-violet-600/20 flex items-center justify-center">
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#a78bfa" strokeWidth="2.5">
                  <polyline points="4 17 10 11 4 5"/>
                  <line x1="12" y1="19" x2="20" y2="19"/>
                </svg>
              </div>
              <code className="text-sm font-mono text-zinc-300">
                <span className="text-zinc-600">$</span>{' '}
                <span className="text-violet-400">npx</span>{' '}
                <span className="text-zinc-200">stylekit-ai pull vercel</span>
              </code>
            </div>
          </div>

          {/* Right: Code preview */}
          <div className="relative">
            <div className="absolute -inset-4 bg-violet-600/5 rounded-3xl blur-xl" />
            <div className="relative">
              <CodeBlock
                code={sampleDesignMd}
                language="markdown"
                filename="DESIGN.md"
              />
              {/* Floating badges */}
              <div className="absolute -top-3 -right-3 flex items-center gap-1.5 px-3 py-1.5 bg-emerald-500/20 border border-emerald-500/30 rounded-full text-emerald-400 text-xs font-medium">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                Extracted in 0.8s
              </div>
              <div className="absolute -bottom-3 -left-3 flex items-center gap-1.5 px-3 py-1.5 bg-violet-500/20 border border-violet-500/30 rounded-full text-violet-300 text-xs font-medium">
                <svg width="10" height="10" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/>
                </svg>
                Claude Code ready
              </div>
            </div>
          </div>
        </div>

        {/* Trusted by / logos row */}
        <div className="mt-16 md:mt-20">
          <p className="text-center text-xs text-zinc-600 uppercase tracking-widest mb-6">Works with your favorite AI coding tools</p>
          <div className="flex flex-wrap items-center justify-center gap-3">
            {[
              { name: 'Claude Code', color: 'text-orange-300 border-orange-500/20 bg-orange-500/5' },
              { name: 'Cursor', color: 'text-blue-300 border-blue-500/20 bg-blue-500/5' },
              { name: 'GitHub Copilot', color: 'text-zinc-300 border-zinc-600/40 bg-zinc-500/5' },
              { name: 'Windsurf', color: 'text-cyan-300 border-cyan-500/20 bg-cyan-500/5' },
              { name: 'Gemini CLI', color: 'text-green-300 border-green-500/20 bg-green-500/5' },
              { name: 'Cody', color: 'text-violet-300 border-violet-500/20 bg-violet-500/5' },
            ].map((tool) => (
              <span key={tool.name} className={`px-3.5 py-1.5 rounded-full border text-xs font-medium ${tool.color} transition-all duration-200 hover:scale-105`}>
                {tool.name}
              </span>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}


